name: progetto_grouply
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Utility
  image_picker: ^1.0.7
  file_picker: ^10.3.7

  # Date
  intl: ^0.20.2

  # Google
  google_sign_in: ^7.2.0
  # Nota: Le dipendenze specifiche (_android, _ios, etc) sono incluse in google_sign_in,
  # ma se le hai messe per risolvere conflitti lasciale pure.
  google_sign_in_android: ^7.2.7
  google_sign_in_ios: ^6.2.4
  google_sign_in_web: ^1.1.0
  google_sign_in_platform_interface: ^3.1.0
  google_identity_services_web: ^0.3.3+1

  # Map & Location
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  http: ^1.2.0
  # geocoding: ^2.1.1 # Disabilitato per usare Nominatim (HTTP) su emulatore

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  # ðŸ‘‡ AGGIUNTO PER LA SPLASH SCREEN
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fonts/
    - lib/assets/logo/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700

# CONFIGURAZIONE SPLASH SCREEN
flutter_native_splash:
  color: "#E91E63"
  image: lib/assets/logo/logo_nobg.png
  android_12:
    image: lib/assets/logo/logo_nobg.png
    color: "#E91E63"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/assets/logo/app_icon.png"
  adaptive_icon_foreground: "lib/assets/logo/logo_nobg.png"
  adaptive_icon_background: "#333333"
  min_sdk_android: 21